routine: deep_learning
params:
    data_dir: "C:\\Users\\Jeongwon MIN\\work\\personal\\midi_generation_experiments\\data\\small_with_andes_test"
    dataset_name: "hooktheory"
    npy_dir: #"/Users/MIN/my_workspace/MidiGeneration/results/20180324-154201/npy_data" # npy data dir
    result_dir: "C:\\Users\\Jeongwon MIN\\work\\personal\\midi_generation_experiments\\results"
    sample_dir: "C:\\Users\\Jeongwon MIN\\work\\personal\\midi_generation_experiments\\results\\samples"
    pretraining_epoch: 0 # 10
    fine_tuning_epoch: 100 # 10
    class: "SmallDataMidiNet"
    learning_params:
        learning_rate: 0.00005
        beta1: 0.5
    model_params:
        batch_size: 72
        sample_size: 72
        output_w: 16
        output_h: 128
        y_dim: 13
        prev_dim: 1
        z_dim: 100
        gf_dim: 64
        df_dim: 64
        gfc_dim: 1024
        dfc_dim: 1024
        c_dim: 1
        small_rate: 10 # novel:small=10:1
        pretrained_model: "C:\\Users\\Jeongwon MIN\\work\\personal\\midi_generation_experiments\\pretrained_model\\checkpoint_20epoch" # 20180507-001253: 10epoch+10epoch # pretained model file(result/yyyyddmm-HHMMSS/checkpoint
        threshold: 0.4 
        alpha_blend: 0.3
        use_fake: true